bind 127.0.0.1
bind 0.0.0.0
port 6379
# 设置密码
requirepass Tangke666!
# 设置数据库数量
databases 16
# 设置日志级别
loglevel notice
# 设置日志文件
logfile "redis.log"
# 开启保护模式
protected-mode yes


# 2. 禁用高危命令（防止被黑客一键删库）
# 禁用 FLUSHALL 命令
rename-command FLUSHALL ""
# 禁用 FLUSHDB 命令
rename-command FLUSHDB ""
# 禁用 CONFIG 命令
rename-command CONFIG ""
# 禁用 KEYS 命令
rename-command KEYS ""

# 持久化管理
# 设置持久化
appendonly yes
# 设置持久化文件
appendfilename "appendonly.aof"
# 设置持久化策略
appendfsync everysec

# 4. 内存管理（防止 OOM 导致宿主机崩溃）
# maxmemory 512mb #设置最大内存
# maxmemory-policy allkeys-lru #设置最大内存策略
